#! /bin/sh
export PATH=$PATH:/mongodb/bin
export ASPNETCORE_ENVIRONMENT=Development
export PROJECT=/projects/agile-retro
echo "This should be running in the docker container not the host"
cd $PROJECT
bash