#! /bin/sh
echo '******'
echo 'testing the DB components'
dotnet test $PROJECT/Retrospective.Data.Test/Retrospective.Data.Test.csproj
echo '******'
echo 'testing the domain layer components'
dotnet test $PROJECT/Retrospective.Domain.Test/Retrospective.Domain.Test.csproj
echo '******'
echo 'testing the app logic in C#'
dotnet test $PROJECT/apptest/apptest.csproj
echo '******'
echo 'testing the UI'
cd $PROJECT/web/client
ng test --watch=false

