#!/usr/bin/env groovy

import hudson.model.*
import hudson.EnvVars
import hudson.FilePath

try {
  node {
    def demodataimage

    stage ('Clone repo'){
      checkout scm
    }
    stage('Docker Build'){
         
          demodataimage = docker.build("agileretro-demodata", "-f scripts/demodata/demodata.dockerfile .")
    }
    stage ('Build'){
      demodataimage.inside('-u root'){
        sh 'ls /agile-retro/tools/demodata'
        sh 'dotnet --version'
        sh 'dotnet build /agile-retro/tools/demodata/demodata.csproj'
      }
    }
    stage('Test'){
      demodataimage.inside('-u root'){
      }
    }
    stage('Run')
    {
      withCredentials([secret(credentialsId: 'agile-retro-prod-connectionstring', secret: 'connection-string')]) {
          sh 'docker run -rm -u root -e DB_NAME=agile-retro-prod -e DB_CONNECTIONSTRING=${connection-string} agileretro-demodata dotnet run /agile-retro/tools/demodata/demodata.csproj'
      }
      
    }
  }
}
catch (err){
    throw err

}