#! /bin/sh
export PATH=$PATH:/mongodb/bin
mongod --dbpath "/projects/agile-retro/data"
export ASPNETCORE_ENVIRONMENT=Development
echo "This should be running in the docker container not the host"
bash