#!/usr/bin/env groovy

import hudson.model.*
import hudson.EnvVars
import hudson.FilePath

try {
  node {
    def agileretroimage

    stage ('Clone repo'){
      checkout scm
    }

    stage('Docker Build'){
         
          agileretroimage = docker.build("agileretro", "-f scripts/test/ci-build.dockerfile")
    }

    stage ('Build')
    {
      agileretroimage.inside(){
        sh 'ls /agile-retro'
        sh 'dotnet --version'
        sh 'whoami'
        sh 'dotnet build /agile-retro/app/app.csproj'
        sh 'ng --version'
        sh 'ls -al /agile-retro/web/client'
        sh 'cd /agile-retro/web/client && npm install && ng build'
      }
    }
    stage('Test'){
      agileretroimage.indside(){
        sh 'mkdir /agile-retro/data'
        sh '/mongodb/bin/mongod --dbpath "/agile-retro/data"  --bind_ip 0.0.0.0  &'
        sh 'dotnet test /agile-retro/Retrospective.Data.Test/Retrospective.Data.Test.csproj'
        sh 'dotnet test /agile-retro/Retrospective.Domain.Test/Retrospective.Domain.Test.csproj'
        sh 'dotnet test /agile-retro/apptest/apptest.csproj'
        sh 'dotnet run -p /agile-retro/tools/testdata/testdata.csproj'
        sh 'cd /agile-retro/web/client && ng test  --watch=false'
      }
    }
  }
}
catch (err){
    throw err

}